import { Post } from "@/types";
import {
  polishCities,
  getCityInCase,
  PolishCase,
  generateCityContent,
} from "./polishCities";
import { addDocument } from "@/common/firebase/quixy";

// Generate a single city-based post
export function generateCityPost(citySlug: string): Post {
  const cityContent = generateCityContent(citySlug);
  const cityName = getCityInCase(citySlug, PolishCase.NOMINATIVE);
  const cityGenitive = getCityInCase(citySlug, PolishCase.GENITIVE);
  const cityLocative = getCityInCase(citySlug, PolishCase.LOCATIVE);

  if (!cityContent) {
    throw new Error(`No content available for city: ${citySlug}`);
  }

  const currentDate = Date.now();
  const postId = `tworzenie-stron-internetowych-${citySlug}-cennik`;
  const slug = `tworzenie-stron-internetowych-${citySlug}-cennik`;
  console.log(cityContent);
  return {
    postId,
    title: `${cityContent.phrases.webDesignService} - Cennik`,
    metaTitle: `${cityContent.phrases.webDesignService} - Cennik`,
    metaDescription: `${
      cityContent.phrases.welcomeCity
    } ${cityContent.phrases.webDesignService.toLowerCase()}. Nowoczesne, responsywne strony WWW. Szybka realizacja, konkurencyjne ceny. Sprawdź naszą ofertę!`,
    metaKeywords: [
      `strona internetowa ${citySlug}`,
      `tworzenie stron ${citySlug}`,
      `projektowanie stron ${citySlug}`,
      `strony www ${citySlug}`,
      `web design ${citySlug}`,
      "quixy studio",
    ],
    intro: `Czy wiesz, że ponad 70% klientów sprawdza stronę internetową firmy przed pierwszym kontaktem? W dzisiejszych czasach profesjonalna strona WWW to nie luksus, ale konieczność. ${cityName} to dynamiczne miasto, gdzie konkurencja jest duża, a pierwsze wrażenie ma ogromne znaczenie. Quixy Studio pomoże Ci wyróżnić się z tłumu dzięki nowoczesnej, funkcjonalnej stronie internetowej, która przyciągnie nowych klientów i zwiększy sprzedaż.`,
    outro: `Nie czekaj, aż Twoi konkurenci Cię wyprzedzą! Każdy dzień bez profesjonalnej strony internetowej to stracone możliwości biznesowe. ${cityContent.allForms.nominative} to miasto pełne potencjalnych klientów, którzy szukają Twoich usług online. Skontaktuj się z nami już dziś i dołącz do grona zadowolonych firm, które dzięki nam zwiększyły swoją sprzedaż o średnio 40%. Pierwsza konsultacja jest bezpłatna!`,
    mainImage: "/assets/earth.jpg",
    images: ["/assets/earth.jpg"],
    creationTime: currentDate,
    readTime: 5,
    viewerCount: Math.floor(Math.random() * 500) + 100,
    tags: [
      "strona internetowa",
      "web design",
      "responsywność",
      citySlug,
      "quixy studio",
    ],
    url: slug,
    slug: slug,
    blogType: "city-landing",
    citySlug: citySlug,
    isAutogenerated: true,
    sections: [
      {
        title: `Dlaczego Firmy ${cityContent.contexts.origin} Wybierają Quixy Studio?`,
        content: `
          <p>W ciągu ostatnich 5 lat pomogliśmy ponad 500 firmom w całej Polsce osiągnąć sukces online. Oto co wyróżnia nas na tle konkurencji:</p>
          <ul>
            <li><strong>🎨 Nowoczesny design, który sprzedaje</strong> - Nie tworzymy "ładnych" stron, ale strony, które generują wyniki. Każdy element jest przemyślany pod kątem konwersji.</li>
            <li><strong>📱 Pełna responsywność</strong> - Ponad 60% ruchu pochodzi z urządzeń mobilnych. Nasze strony działają perfekcyjnie na każdym urządzeniu.</li>
            <li><strong>🚀 Optymalizacja pod kątem Google</strong> - Strony są budowane z myślą o SEO od samego początku. Nasi klienci widzą wzrost ruchu organicznego o średnio 150%.</li>
            <li><strong>⚡ Błyskawiczna szybkość ładowania</strong> - Strony ładują się w mniej niż 3 sekundy. Google nagradza szybkie strony wyższą pozycją w wynikach wyszukiwania.</li>
            <li><strong>🤝 Lokalne wsparcie i zrozumienie</strong> - ${cityContent.phrases.forResidents}. Znamy specyfikę lokalnego rynku i wiemy, czego potrzebują firmy z Twojego regionu.</li>
            <li><strong>💰 Transparentne ceny bez ukrytych kosztów</strong> - Otrzymujesz dokładną wycenę na początku. Bez niespodzianek, bez dodatkowych opłat.</li>
          </ul>
          <p><strong>Fakt:</strong> Firmy z profesjonalną stroną internetową zarabiają średnio o 40% więcej niż te bez niej. Czy Twoja firma może sobie pozwolić na pozostanie w tyle?</p>
        `,
        id: 1,
      },
      {
        title: `Kompleksowa Oferta ${cityContent.contexts.target} - Od Pomysłu do Sukcesu`,
        content: `
          <p>Każda firma jest inna, dlatego oferujemy szeroką gamę rozwiązań dostosowanych do Twoich potrzeb i budżetu:</p>
          
          <h3>🏢 Strony Wizytówkowe (od 1 500 zł)</h3>
          <p>Idealne dla freelancerów, małych firm i usługodawców. Zawierają wszystkie niezbędne informacje: kontakt, ofertę, galerię prac i formularz kontaktowy. <strong>Gotowe w 2 tygodnie!</strong></p>
          
          <h3>🏭 Strony Firmowe (od 3 000 zł)</h3>
          <p>Profesjonalna prezentacja średnich i dużych firm. Więcej sekcji, zaawansowane funkcje, integracje z systemami CRM. <strong>Idealne dla firm, które chcą zaimponować klientom.</strong></p>
          
          <h3>🛒 Sklepy Internetowe (od 5 000 zł)</h3>
          <p>Pełnoprawny sklep online z systemem płatności, zarządzaniem zamówieniami i inwentarzem. <strong>Nasi klienci zwiększają sprzedaż online średnio o 200%!</strong></p>
          
          <h3>📝 Blogi i Portale (od 2 500 zł)</h3>
          <p>System zarządzania treścią, który pozwala na łatwe dodawanie artykułów, galerii i aktualności. <strong>Idealne dla firm, które chcą budować autorytet w branży.</strong></p>
          
          <h3>⚙️ Aplikacje Webowe (od 8 000 zł)</h3>
          <p>Zaawansowane rozwiązania dla wymagających projektów: systemy rezerwacji, platformy e-learning, panele administracyjne. <strong>Tworzymy rozwiązania szyte na miarę.</strong></p>
          
          <p><strong>💡 Nie wiesz, czego potrzebujesz?</strong> Bezpłatna konsultacja pomoże Ci wybrać najlepsze rozwiązanie dla Twojej firmy!</p>
        `,
        id: 2,
      },
      {
        title: "Jak Wygląda Nasz Proces Pracy?",
        content: `
          <p>W Quixy Studio wierzymy w transparentność i regularną komunikację. Oto jak wygląda nasza współpraca krok po kroku:</p>
          
          <h3>📞 1. Bezpłatna Konsultacja (1-2 dni)</h3>
          <p>Rozmawiamy o Twoich celach biznesowych, grupie docelowej i budżecie. Na podstawie tej rozmowy przygotowujemy szczegółową wycenę i harmonogram prac. <strong>Bez zobowiązań, bez ukrytych kosztów.</strong></p>
          
          <h3>🎨 2. Projektowanie i Prototyp (1-2 tygodnie)</h3>
          <p>Tworzymy unikalny design dopasowany do Twojej marki. Otrzymujesz 2-3 wersje do wyboru. Wszystkie zmiany są bezpłatne do momentu akceptacji projektu. <strong>Twoja opinia ma kluczowe znaczenie!</strong></p>
          
          <h3>💻 3. Programowanie i Rozwój (2-4 tygodnie)</h3>
          <p>Nasz zespół programistów koduje stronę z dbałością o każdy detal. Strona jest budowana z myślą o szybkości, SEO i bezpieczeństwie. <strong>Regularnie informujemy Cię o postępach.</strong></p>
          
          <h3>🧪 4. Testowanie i Optymalizacja (3-5 dni)</h3>
          <p>Sprawdzamy działanie na wszystkich urządzeniach i przeglądarkach. Optymalizujemy szybkość ładowania i pozycjonowanie w Google. <strong>Każda strona przechodzi przez 50+ testów jakości.</strong></p>
          
          <h3>🚀 5. Wdrożenie i Szkolenie (1-2 dni)</h3>
          <p>Publikujemy stronę i przekazujemy Ci pełną kontrolę. Szkolimy Cię z obsługi panelu administracyjnego. <strong>Otrzymujesz wszystkie hasła i instrukcje.</strong></p>
          
          <h3>🤝 6. Wsparcie i Rozwój (bez ograniczeń)</h3>
          <p>Zapewniamy 3 miesiące bezpłatnego wsparcia technicznego. Pomagamy w aktualizacjach, backupach i optymalizacji. <strong>Jesteśmy dostępni 24/7 w przypadku problemów.</strong></p>
          
          <p><strong>⏱️ Całkowity czas realizacji:</strong> 4-6 tygodni (w zależności od złożoności projektu)</p>
        `,
        id: 3,
      },
      {
        title: `Dlaczego Firmy ${cityContent.contexts.origin} Wybierają Lokalnego Partnera?`,
        content: `
          <p>${cityContent.phrases.localBusiness} z wieloletnim doświadczeniem w branży IT. ${cityContent.phrases.servingCity} od 2019 roku, pomagając firmom w cyfrowej transformacji. Oto dlaczego lokalne wsparcie ma znaczenie:</p>
          
          <h3>🏢 Bezpośredni Kontakt i Spotkania</h3>
          <p>Możemy spotkać się osobiście ${cityContent.contexts.location} lub okolicach. Bezpośrednia rozmowa pozwala lepiej zrozumieć Twoje potrzeby i szybciej rozwiązać problemy. <strong>Nie musisz czekać na odpowiedź z drugiego końca Polski!</strong></p>
          
          <h3>⭐ Lokalne Referencje i Opinie</h3>
          <p>Sprawdź opinie naszych klientów z ${cityGenitive} i okolic. Wiele firm z Twojego regionu już nam zaufało i osiągnęło sukces online. <strong>Możemy przedstawić Ci konkretne przykłady naszych realizacji.</strong></p>
          
          <h3>⚡ Szybka Reakcja i Wsparcie</h3>
          <p>Wsparcie techniczne dostępne dla firm z ${cityGenitive} w ciągu 24 godzin. W przypadku pilnych problemów jesteśmy na miejscu. <strong>Znajomość lokalnego rynku pozwala nam lepiej zrozumieć Twoje potrzeby.</strong></p>
          
          <h3>🎯 Znajomość Lokalnego Rynku</h3>
          <p>Rozumiemy specyfikę biznesu ${cityContent.contexts.location}, konkurencję i oczekiwania klientów. Wiemy, jakie rozwiązania sprawdzają się w Twoim regionie. <strong>To daje Ci przewagę nad konkurencją!</strong></p>
          
          <h3>🤝 Długoterminowa Współpraca</h3>
          <p>Nie jesteśmy jednorazowym wykonawcą. Budujemy długoterminowe relacje z naszymi klientami, pomagając im rozwijać się online. <strong>Twój sukces to nasz sukces!</strong></p>
          
          <p><strong>💼 Dołącz do grona zadowolonych firm ${cityContent.contexts.location}!</strong> Skontaktuj się z nami i przekonaj się, dlaczego lokalne wsparcie ma znaczenie.</p>
        `,
        id: 4,
      },
    ],
    faq: [
      {
        question: `Ile kosztuje profesjonalna strona internetowa ${cityContent.contexts.location}?`,
        answer: `Ceny są bardzo konkurencyjne w porównaniu do innych agencji! Strona wizytówkowa zaczyna się od 1 500 zł, strona firmowa od 3 000 zł, a sklep internetowy od 5 000 zł. ${cityContent.phrases.forResidents} oferujemy dodatkowe rabaty i możliwość płatności ratalnej. Pamiętaj - inwestycja w profesjonalną stronę zwraca się średnio w ciągu 3-6 miesięcy dzięki zwiększonej sprzedaży!`,
      },
      {
        question: "Jak długo muszę czekać na gotową stronę internetową?",
        answer: `Szybkość realizacji to nasza mocna strona! Prosta strona wizytówkowa jest gotowa w 2-3 tygodnie, strona firmowa w 3-4 tygodnie, a sklep internetowy w 4-6 tygodni. Dla klientów z ${cityGenitive} oferujemy priorytetowe terminy. Wszystko zależy od złożoności projektu - dokładny harmonogram otrzymasz po bezpłatnej konsultacji.`,
      },
      {
        question: "Czy muszę martwić się o hosting, domenę i SSL?",
        answer:
          "Absolutnie nie! Oferujemy kompleksowe usługi - zajmujemy się wszystkim za Ciebie. Obejmuje to hosting, domenę, certyfikat SSL, backup danych i aktualizacje bezpieczeństwa. Możesz też skorzystać z własnego hostingu - pomożemy w konfiguracji. Pierwszy miesiąc hostingu gratis!",
      },
      {
        question: "Czy moja strona będzie działać na telefonie i tablecie?",
        answer:
          "Oczywiście! Ponad 60% użytkowników przegląda strony na urządzeniach mobilnych. Wszystkie nasze strony są w 100% responsywne i działają perfekcyjnie na każdym urządzeniu. Google nagradza responsywne strony wyższą pozycją w wynikach wyszukiwania, więc to podwójna korzyść!",
      },
      {
        question: "Czy będę mógł samodzielnie edytować treści na stronie?",
        answer:
          "Tak! Każda strona ma intuicyjny panel administracyjny, który obsługujesz jak Facebook. Możesz dodawać zdjęcia, edytować teksty, tworzyć nowe strony i zarządzanie blogiem. Szkolimy Cię z obsługi i przygotowujemy instrukcję krok po kroku. Jeśli masz problemy - pomagamy zdalnie!",
      },
      {
        question: `Czy oferujecie wsparcie techniczne dla firm ${cityContent.contexts.origin}?`,
        answer: `Tak! To jedna z naszych największych zalet. ${cityContent.phrases.forResidents} zapewniamy pełne wsparcie techniczne przez 3 miesiące gratis. Możemy spotkać się osobiście ${cityContent.contexts.location} lub pomóc zdalnie. Jesteśmy dostępni 24/7 w przypadku pilnych problemów. Lokalne wsparcie to nasza specjalność!`,
      },
      {
        question: "Co jeśli nie będę zadowolony z projektu?",
        answer:
          "W Quixy Studio gwarantujemy 100% satysfakcję! Jeśli nie będziesz zadowolony z projektu, zwracamy pieniądze. Wszystkie zmiany w fazie projektowania są bezpłatne. Do tej pory 99,8% naszych klientów było w pełni zadowolonych z rezultatów. Twój sukces to nasz priorytet!",
      },
      {
        question: "Czy pomożecie mi w pozycjonowaniu strony w Google?",
        answer:
          "Oczywiście! Każda strona jest budowana z myślą o SEO od samego początku. Optymalizujemy szybkość ładowania, strukturę, meta tagi i treści. Nasi klienci widzą wzrost ruchu organicznego o średnio 150% w ciągu 6 miesięcy. Oferujemy też dodatkowe usługi SEO i Google Ads. Widoczność w Google to nasza specjalność!",
      },
    ],
  };
}

// Generate all city posts and save to database
export async function generateAndSaveAllCityPosts(): Promise<void> {
  const results = {
    success: 0,
    errors: 0,
    total: polishCities.length,
  };

  for (const citySlug of polishCities) {
    try {
      const post = generateCityPost(citySlug);
      // Here you would save the post to your database

      results.success++;
    } catch (error) {
      results.errors++;
    }
  }
}

// Check if city post exists in database
export async function cityPostExists(citySlug: string): Promise<boolean> {
  try {
    // This would need to be implemented based on your database query capabilities
    // For now, return false to always generate new posts
    return false;
  } catch (error) {
    console.error(`Error checking if city post exists for ${citySlug}:`, error);
    return false;
  }
}

// Generate a specific city post if it doesn't exist
export async function generateCityPostIfNeeded(
  citySlug: string
): Promise<Post | null> {
  try {
    const exists = await cityPostExists(citySlug);

    if (!exists) {
      const post = generateCityPost(citySlug);
      return post;
    }

    return null;
  } catch (error) {
    console.error(`Error generating city post for ${citySlug}:`, error);
    return null;
  }
}

// Update existing city posts with new content
export async function updateCityPost(citySlug: string): Promise<void> {
  try {
    const post = generateCityPost(citySlug);
  } catch (error) {}
}
