// Major cities in Poland (not villages) - population over 50,000
export const polishCities = [
  "warszawa",
  "krakow",
  "lodz",
  "wroclaw",
  "poznan",
  "gdansk",
  "szczecin",
  "bydgoszcz",
  "lublin",
  "katowice",
  "bialystok",
  "gdynia",
  "czestochowa",
  "radom",
  "sosnowiec",
  "torun",
  "kielce",
  "gliwice",
  "zabrze",
  "bytom",
  "bielsko-biala",
  "olsztyn",
  "rzeszow",
  "ruda-slaska",
  "rybnik",
  "tychy",
  "dabrowa-gornicza",
  "plock",
  "elblag",
  "walbrzych",
  "wloclawek",
  "tarnow",
  "chorzow",
  "kalisz",
  "koszalin",
  "legnica",
  "grudziadz",
  "slupsk",
  "jaworzno",
  "jastrzebie-zdroj",
  "nowy-sacz",
  "jelenia-gora",
  "konin",
  "piotrkow-trybunalski",
  "inowroclaw",
  "lubin",
  "kedzierzyn-kozle",
  "ostrowiec-swietokrzyski",
  "gniezno",
  "stargard",
  "suwalki",
  "siedlce",
  "ostrow-wielkopolski",
  "zielona-gora",
  "przemysl",
  "bielawa",
  "starachowice",
  "pulawy",
  "lomza",
  "swinoujscie",
  "pabianice",
  "zgierz",
  "tomaszow-mazowiecki",
  "leszno",
  "zary",
  "mielec",
  "wejherowo",
  "ostroleka",
  "ciechanow",
  "zyrardow",
  "stalowa-wola",
  "belchatow",
  "tczew",
  "malbork",
  "chojnice",
  "kwidzyn",
  "elk",
  "ostroda",
  "ilawa",
  "debica",
  "krosno",
  "sanok",
  "zakopane",
  "nowy-targ",
  "opole",
  "nysa",
  "klodzko",
  "wodzislaw-slaski",
  "cieszyn",
  "pszczyna",
  "oswiecim",
  "tarnowskie-gory",
  "mikolow",
  "zawiercie",
  "olkusz",
  "myszkow",
  "lebork",
  "ustka",
  "kolobrzeg",
  "kamien-pomorski",
  "szczecinek",
  "walcz",
  "pila",
  "czarnkow",
  "wagrowiec",
  "miedzychod",
  "srem",
  "sroda-wielkopolska",
  "trzcianka",
  "oborniki",
  "sieradz",
  "skierniewice",
  "lowicz",
  "ozorkow",
  "kutno",
  "leczyca",
  "wielun",
  "pajeczno",
  "rawa-mazowiecka",
  "szadek",
  "opoczno",
  "tomaszow-lubelski",
  "lubartow",
  "swidnik",
  "krasnystaw",
  "chelm",
  "zamosc",
  "hrubieszow",
  "bilgoraj",
  "sandomierz",
  "tarnobrzeg",
  "stalowa-wola",
];

// Convert city name to URL-friendly slug
export function cityToSlug(city: string): string {
  // Ensure city is a valid city slug (from polishCities)
  if (!polishCities.includes(city)) {
    throw new Error(`Invalid city: ${city}`);
  }
  return `tworzenie-stron-internetowych-${city}-cennik`;
}

export function slugToCity(slug: string): string | null {
  // Match the pattern and extract the city slug
  const match = slug.match(
    /^tworzenie-stron-internetowych-([a-z0-9-]+)-cennik$/
  );
  if (!match) {
    return null;
  }
  const cityName = match[1];
  return polishCities.includes(cityName) ? cityName : null;
}

// Get city display name (capitalize first letter)
export function getCityDisplayName(city: string): string {
  return city
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
export function getCityNominative(city: string): string {
  // Returns the nominative (mianownik) form of the city, or the display name if not found in declensions
  if (cityDeclensions[city] && cityDeclensions[city].nominative) {
    return cityDeclensions[city].nominative;
  }
  // fallback: prettify the slug
  return getCityDisplayName(city);
}

// Check if slug is a city-based slug
export function isCitySlug(slug: string): boolean {
  return (
    slug.startsWith("tworzenie-stron-internetowych-") &&
    slugToCity(slug) !== null
  );
}

// Generate all city slugs
export function getAllCitySlugs(): string[] {
  return polishCities.map(cityToSlug);
}

// Polish grammatical cases enum
export enum PolishCase {
  NOMINATIVE = "nominative", // mianownik – kto? co?
  GENITIVE = "genitive", // dopełniacz – kogo? czego?
  DATIVE = "dative", // celownik – komu? czemu?
  ACCUSATIVE = "accusative", // biernik – kogo? co?
  INSTRUMENTAL = "instrumental", // narzędnik – z kim? z czym?
  LOCATIVE = "locative", // miejscownik – o kim? o czym?
  VOCATIVE = "vocative", // wołacz – o!
}

// City declension interface
export interface CityDeclension {
  nominative: string; // kto? co?
  genitive: string; // kogo? czego?
  dative: string; // komu? czemu?
  accusative: string; // kogo? co?
  instrumental: string; // z kim? z czym?
  locative: string; // o kim? o czym?
  vocative: string; // o!
}

// Comprehensive declension map for Polish cities
export const cityDeclensions: Record<string, CityDeclension> = {
  warszawa: {
    nominative: "Warszawa",
    genitive: "Warszawy",
    dative: "Warszawie",
    accusative: "Warszawę",
    instrumental: "Warszawą",
    locative: "Warszawie",
    vocative: "Warszawo",
  },
  krakow: {
    nominative: "Kraków",
    genitive: "Krakowa",
    dative: "Krakowowi",
    accusative: "Kraków",
    instrumental: "Krakowem",
    locative: "Krakowie",
    vocative: "Krakowie",
  },
  lodz: {
    nominative: "Łódź",
    genitive: "Łodzi",
    dative: "Łodzi",
    accusative: "Łódź",
    instrumental: "Łodzią",
    locative: "Łodzi",
    vocative: "Łodzi",
  },
  wroclaw: {
    nominative: "Wrocław",
    genitive: "Wrocławia",
    dative: "Wrocławiowi",
    accusative: "Wrocław",
    instrumental: "Wrocławiem",
    locative: "Wrocławiu",
    vocative: "Wrocławiu",
  },
  poznan: {
    nominative: "Poznań",
    genitive: "Poznania",
    dative: "Poznaniowi",
    accusative: "Poznań",
    instrumental: "Poznaniem",
    locative: "Poznaniu",
    vocative: "Poznaniu",
  },
  gdansk: {
    nominative: "Gdańsk",
    genitive: "Gdańska",
    dative: "Gdańskowi",
    accusative: "Gdańsk",
    instrumental: "Gdańskiem",
    locative: "Gdańsku",
    vocative: "Gdańsku",
  },
  szczecin: {
    nominative: "Szczecin",
    genitive: "Szczecina",
    dative: "Szczecinowi",
    accusative: "Szczecin",
    instrumental: "Szczecinem",
    locative: "Szczecinie",
    vocative: "Szczecinie",
  },
  bydgoszcz: {
    nominative: "Bydgoszcz",
    genitive: "Bydgoszczy",
    dative: "Bydgoszczy",
    accusative: "Bydgoszcz",
    instrumental: "Bydgoszczą",
    locative: "Bydgoszczy",
    vocative: "Bydgoszczy",
  },
  lublin: {
    nominative: "Lublin",
    genitive: "Lublina",
    dative: "Lublinowi",
    accusative: "Lublin",
    instrumental: "Lublinem",
    locative: "Lublinie",
    vocative: "Lublinie",
  },
  katowice: {
    nominative: "Katowice",
    genitive: "Katowic",
    dative: "Katowicom",
    accusative: "Katowice",
    instrumental: "Katowicami",
    locative: "Katowicach",
    vocative: "Katowice",
  },
  bialystok: {
    nominative: "Białystok",
    genitive: "Białegostoku",
    dative: "Białemustokowi",
    accusative: "Białystok",
    instrumental: "Białymstokiem",
    locative: "Białymstoku",
    vocative: "Białymstoku",
  },
  gdynia: {
    nominative: "Gdynia",
    genitive: "Gdyni",
    dative: "Gdyni",
    accusative: "Gdynię",
    instrumental: "Gdynią",
    locative: "Gdyni",
    vocative: "Gdynio",
  },
  czestochowa: {
    nominative: "Częstochowa",
    genitive: "Częstochowy",
    dative: "Częstochowie",
    accusative: "Częstochowę",
    instrumental: "Częstochową",
    locative: "Częstochowie",
    vocative: "Częstochowo",
  },
  radom: {
    nominative: "Radom",
    genitive: "Radomia",
    dative: "Radomiowi",
    accusative: "Radom",
    instrumental: "Radomiem",
    locative: "Radomiu",
    vocative: "Radomie",
  },
  sosnowiec: {
    nominative: "Sosnowiec",
    genitive: "Sosnowca",
    dative: "Sosnowcowi",
    accusative: "Sosnowiec",
    instrumental: "Sosnowcem",
    locative: "Sosnowcu",
    vocative: "Sosnowcu",
  },
  torun: {
    nominative: "Toruń",
    genitive: "Torunia",
    dative: "Toruniowi",
    accusative: "Toruń",
    instrumental: "Toruniem",
    locative: "Toruniu",
    vocative: "Toruniu",
  },
  kielce: {
    nominative: "Kielce",
    genitive: "Kielc",
    dative: "Kielcom",
    accusative: "Kielce",
    instrumental: "Kielcami",
    locative: "Kielcach",
    vocative: "Kielce",
  },
  gliwice: {
    nominative: "Gliwice",
    genitive: "Gliwic",
    dative: "Gliwicom",
    accusative: "Gliwice",
    instrumental: "Gliwicami",
    locative: "Gliwicach",
    vocative: "Gliwice",
  },
  zabrze: {
    nominative: "Zabrze",
    genitive: "Zabrza",
    dative: "Zabrzowi",
    accusative: "Zabrze",
    instrumental: "Zabrzem",
    locative: "Zabrzu",
    vocative: "Zabrze",
  },
  bytom: {
    nominative: "Bytom",
    genitive: "Bytomia",
    dative: "Bytomiowi",
    accusative: "Bytom",
    instrumental: "Bytomiem",
    locative: "Bytomiu",
    vocative: "Bytomie",
  },
  "bielsko-biala": {
    nominative: "Bielsko-Biała",
    genitive: "Bielska-Białej",
    dative: "Bielsku-Białej",
    accusative: "Bielsko-Białą",
    instrumental: "Bielskiem-Białą",
    locative: "Bielsku-Białej",
    vocative: "Bielsko-Biała",
  },
  olsztyn: {
    nominative: "Olsztyn",
    genitive: "Olsztyna",
    dative: "Olsztynowi",
    accusative: "Olsztyn",
    instrumental: "Olsztynem",
    locative: "Olsztynie",
    vocative: "Olsztynie",
  },
  rzeszow: {
    nominative: "Rzeszów",
    genitive: "Rzeszowa",
    dative: "Rzeszowowi",
    accusative: "Rzeszów",
    instrumental: "Rzeszowem",
    locative: "Rzeszowie",
    vocative: "Rzeszowie",
  },
  grudziadz: {
    nominative: "Grudziądz",
    genitive: "Grudziądza",
    dative: "Grudziądzowi",
    accusative: "Grudziądz",
    instrumental: "Grudziądzem",
    locative: "Grudziądzu",
    vocative: "Grudziądzu",
  },
  "ruda-slaska": {
    nominative: "Ruda Śląska",
    genitive: "Rudy Śląskiej",
    dative: "Rudzie Śląskiej",
    accusative: "Rudę Śląską",
    instrumental: "Rudą Śląską",
    locative: "Rudzie Śląskiej",
    vocative: "Rudo Śląska",
  },
  rybnik: {
    nominative: "Rybnik",
    genitive: "Rybnika",
    dative: "Rybnikowi",
    accusative: "Rybnik",
    instrumental: "Rybnikiem",
    locative: "Rybniku",
    vocative: "Rybniku",
  },
  tychy: {
    nominative: "Tychy",
    genitive: "Tychów",
    dative: "Tychom",
    accusative: "Tychy",
    instrumental: "Tychami",
    locative: "Tychach",
    vocative: "Tychy",
  },
  "dabrowa-gornicza": {
    nominative: "Dąbrowa Górnicza",
    genitive: "Dąbrowy Górniczej",
    dative: "Dąbrowie Górniczej",
    accusative: "Dąbrowę Górniczą",
    instrumental: "Dąbrową Górniczą",
    locative: "Dąbrowie Górniczej",
    vocative: "Dąbrowo Górnicza",
  },
  plock: {
    nominative: "Płock",
    genitive: "Płocka",
    dative: "Płockowi",
    accusative: "Płock",
    instrumental: "Płockiem",
    locative: "Płocku",
    vocative: "Płocku",
  },
  elblag: {
    nominative: "Elbląg",
    genitive: "Elbląga",
    dative: "Elblągiowi",
    accusative: "Elbląg",
    instrumental: "Elblągiem",
    locative: "Elblągu",
    vocative: "Elblągu",
  },
  walbrzych: {
    nominative: "Wałbrzych",
    genitive: "Wałbrzycha",
    dative: "Wałbrzychowi",
    accusative: "Wałbrzych",
    instrumental: "Wałbrzychem",
    locative: "Wałbrzychu",
    vocative: "Wałbrzychu",
  },
  wloclawek: {
    nominative: "Włocławek",
    genitive: "Włocławka",
    dative: "Włocławkowi",
    accusative: "Włocławek",
    instrumental: "Włocławkiem",
    locative: "Włocławku",
    vocative: "Włocławku",
  },
  tarnow: {
    nominative: "Tarnów",
    genitive: "Tarnowa",
    dative: "Tarnowowi",
    accusative: "Tarnów",
    instrumental: "Tarnowem",
    locative: "Tarnowie",
    vocative: "Tarnowie",
  },
  chorzow: {
    nominative: "Chorzów",
    genitive: "Chorzowa",
    dative: "Chorzowowi",
    accusative: "Chorzów",
    instrumental: "Chorzowem",
    locative: "Chorzowie",
    vocative: "Chorzowie",
  },
  kalisz: {
    nominative: "Kalisz",
    genitive: "Kalisza",
    dative: "Kaliszowi",
    accusative: "Kalisz",
    instrumental: "Kaliszem",
    locative: "Kaliszu",
    vocative: "Kaliszu",
  },
  koszalin: {
    nominative: "Koszalin",
    genitive: "Koszalina",
    dative: "Koszalinowi",
    accusative: "Koszalin",
    instrumental: "Koszalinem",
    locative: "Koszalinie",
    vocative: "Koszalinie",
  },
  legnica: {
    nominative: "Legnica",
    genitive: "Legnicy",
    dative: "Legnicy",
    accusative: "Legnicę",
    instrumental: "Legnicą",
    locative: "Legnicy",
    vocative: "Legnico",
  },
  slupsk: {
    nominative: "Słupsk",
    genitive: "Słupska",
    dative: "Słupskowi",
    accusative: "Słupsk",
    instrumental: "Słupskiem",
    locative: "Słupsku",
    vocative: "Słupsku",
  },
  jaworzno: {
    nominative: "Jaworzno",
    genitive: "Jaworzna",
    dative: "Jaworznie",
    accusative: "Jaworzno",
    instrumental: "Jaworznem",
    locative: "Jaworznie",
    vocative: "Jaworzno",
  },
  "jastrzebie-zdroj": {
    nominative: "Jastrzębie-Zdrój",
    genitive: "Jastrzębia-Zdroju",
    dative: "Jastrzębiu-Zdrojowi",
    accusative: "Jastrzębie-Zdrój",
    instrumental: "Jastrzębiem-Zdrojem",
    locative: "Jastrzębiu-Zdroju",
    vocative: "Jastrzębie-Zdroju",
  },
  "nowy-sacz": {
    nominative: "Nowy Sącz",
    genitive: "Nowego Sącza",
    dative: "Nowemu Sączowi",
    accusative: "Nowy Sącz",
    instrumental: "Nowym Sączem",
    locative: "Nowym Sączu",
    vocative: "Nowy Sączu",
  },
  "jelenia-gora": {
    nominative: "Jelenia Góra",
    genitive: "Jeleniej Góry",
    dative: "Jeleniej Górze",
    accusative: "Jelenią Górę",
    instrumental: "Jelenią Górą",
    locative: "Jeleniej Górze",
    vocative: "Jelenia Góro",
  },
  konin: {
    nominative: "Konin",
    genitive: "Konina",
    dative: "Koninowi",
    accusative: "Konin",
    instrumental: "Koninem",
    locative: "Koninie",
    vocative: "Koninie",
  },
  "piotrkow-trybunalski": {
    nominative: "Piotrków Trybunalski",
    genitive: "Piotrkowa Trybunalskiego",
    dative: "Piotrkowowi Trybunalskiemu",
    accusative: "Piotrków Trybunalski",
    instrumental: "Piotrkowem Trybunalskim",
    locative: "Piotrkowie Trybunalskim",
    vocative: "Piotrkowie Trybunalski",
  },
  "zielona-gora": {
    nominative: "Zielona Góra",
    genitive: "Zielonej Góry",
    dative: "Zielonej Górze",
    accusative: "Zieloną Górę",
    instrumental: "Zieloną Górą",
    locative: "Zielonej Górze",
    vocative: "Zielona Góro",
  },
  zakopane: {
    nominative: "Zakopane",
    genitive: "Zakopanego",
    dative: "Zakopanemu",
    accusative: "Zakopane",
    instrumental: "Zakopanem",
    locative: "Zakopanem",
    vocative: "Zakopane",
  },
  opole: {
    nominative: "Opole",
    genitive: "Opola",
    dative: "Opolu",
    accusative: "Opole",
    instrumental: "Opolem",
    locative: "Opolu",
    vocative: "Opole",
  },
  belchatow: {
    nominative: "Bełchatów",
    genitive: "Bełchatowa",
    dative: "Bełchatowowi",
    accusative: "Bełchatów",
    instrumental: "Bełchatowem",
    locative: "Bełchatowie",
    vocative: "Bełchatowie",
  },
  bielawa: {
    nominative: "Bielawa",
    genitive: "Bielawy",
    dative: "Bielawie",
    accusative: "Bielawę",
    instrumental: "Bielawą",
    locative: "Bielawie",
    vocative: "Bielawo",
  },
  bilgoraj: {
    nominative: "Biłgoraj",
    genitive: "Biłgoraja",
    dative: "Biłgorajowi",
    accusative: "Biłgoraj",
    instrumental: "Biłgorajem",
    locative: "Biłgoraju",
    vocative: "Biłgoraju",
  },
  chelm: {
    nominative: "Chełm",
    genitive: "Chełma",
    dative: "Chełmowi",
    accusative: "Chełm",
    instrumental: "Chełmem",
    locative: "Chełmie",
    vocative: "Chełmie",
  },
  chojnice: {
    nominative: "Chojnice",
    genitive: "Chojnic",
    dative: "Chojnicom",
    accusative: "Chojnice",
    instrumental: "Chojnicami",
    locative: "Chojnicach",
    vocative: "Chojnice",
  },
  ciechanow: {
    nominative: "Ciechanów",
    genitive: "Ciechanowa",
    dative: "Ciechanowowi",
    accusative: "Ciechanów",
    instrumental: "Ciechanowem",
    locative: "Ciechanowie",
    vocative: "Ciechanowie",
  },
  cieszyn: {
    nominative: "Cieszyn",
    genitive: "Cieszyna",
    dative: "Cieszynowi",
    accusative: "Cieszyn",
    instrumental: "Cieszynem",
    locative: "Cieszynie",
    vocative: "Cieszynie",
  },
  czarnkow: {
    nominative: "Czarnków",
    genitive: "Czarnkowa",
    dative: "Czarnkowowi",
    accusative: "Czarnków",
    instrumental: "Czarnkowem",
    locative: "Czarnkowie",
    vocative: "Czarnkowie",
  },
  debica: {
    nominative: "Dębica",
    genitive: "Dębicy",
    dative: "Dębicy",
    accusative: "Dębicę",
    instrumental: "Dębicą",
    locative: "Dębicy",
    vocative: "Dębico",
  },
  elk: {
    nominative: "Ełk",
    genitive: "Ełku",
    dative: "Ełkowi",
    accusative: "Ełk",
    instrumental: "Ełkiem",
    locative: "Ełku",
    vocative: "Ełku",
  },
  gniezno: {
    nominative: "Gniezno",
    genitive: "Gniezna",
    dative: "Gnieznu",
    accusative: "Gniezno",
    instrumental: "Gnieznem",
    locative: "Gnieźnie",
    vocative: "Gnieźnie",
  },
  hrubieszow: {
    nominative: "Hrubieszów",
    genitive: "Hrubieszowa",
    dative: "Hrubieszowowi",
    accusative: "Hrubieszów",
    instrumental: "Hrubieszowem",
    locative: "Hrubieszowie",
    vocative: "Hrubieszowie",
  },
  ilawa: {
    nominative: "Iława",
    genitive: "Iławy",
    dative: "Iławie",
    accusative: "Iławę",
    instrumental: "Iławą",
    locative: "Iławie",
    vocative: "Iławo",
  },
  inowroclaw: {
    nominative: "Inowrocław",
    genitive: "Inowrocławia",
    dative: "Inowrocławiowi",
    accusative: "Inowrocław",
    instrumental: "Inowrocławiem",
    locative: "Inowrocławiu",
    vocative: "Inowrocławiu",
  },
  "kamien-pomorski": {
    nominative: "Kamień Pomorski",
    genitive: "Kamienia Pomorskiego",
    dative: "Kamieniowi Pomorskiemu",
    accusative: "Kamień Pomorski",
    instrumental: "Kamieniem Pomorskim",
    locative: "Kamieniu Pomorskim",
    vocative: "Kamieniu Pomorski",
  },
  klodzko: {
    nominative: "Kłodzko",
    genitive: "Kłodzka",
    dative: "Kłodzku",
    accusative: "Kłodzko",
    instrumental: "Kłodzkiem",
    locative: "Kłodzku",
    vocative: "Kłodzku",
  },
  kolobrzeg: {
    nominative: "Kołobrzeg",
    genitive: "Kołobrzegu",
    dative: "Kołobrzegowi",
    accusative: "Kołobrzeg",
    instrumental: "Kołobrzegiem",
    locative: "Kołobrzegu",
    vocative: "Kołobrzegu",
  },
  krasnystaw: {
    nominative: "Krasnystaw",
    genitive: "Krasnegostawu",
    dative: "Krasnemustawowi",
    accusative: "Krasnystaw",
    instrumental: "Krasnymstawem",
    locative: "Krasnymstawie",
    vocative: "Krasnymstawie",
  },
  krosno: {
    nominative: "Krosno",
    genitive: "Krosna",
    dative: "Krosnu",
    accusative: "Krosno",
    instrumental: "Krosnem",
    locative: "Krośnie",
    vocative: "Krośnie",
  },
  kutno: {
    nominative: "Kutno",
    genitive: "Kutna",
    dative: "Kutnu",
    accusative: "Kutno",
    instrumental: "Kutnem",
    locative: "Kutnie",
    vocative: "Kutnie",
  },
  kwidzyn: {
    nominative: "Kwidzyn",
    genitive: "Kwidzyna",
    dative: "Kwidzynowi",
    accusative: "Kwidzyn",
    instrumental: "Kwidzynem",
    locative: "Kwidzynie",
    vocative: "Kwidzynie",
  },
  lebork: {
    nominative: "Lębork",
    genitive: "Lęborka",
    dative: "Lęborkowi",
    accusative: "Lębork",
    instrumental: "Lęborkiem",
    locative: "Lęborku",
    vocative: "Lęborku",
  },
  leczyca: {
    nominative: "Łęczyca",
    genitive: "Łęczycy",
    dative: "Łęczycy",
    accusative: "Łęczycę",
    instrumental: "Łęczycą",
    locative: "Łęczycy",
    vocative: "Łęczyco",
  },
  leszno: {
    nominative: "Leszno",
    genitive: "Leszna",
    dative: "Lesznu",
    accusative: "Leszno",
    instrumental: "Lesznem",
    locative: "Lesznie",
    vocative: "Lesznie",
  },
  lomza: {
    nominative: "Łomża",
    genitive: "Łomży",
    dative: "Łomży",
    accusative: "Łomżę",
    instrumental: "Łomżą",
    locative: "Łomży",
    vocative: "Łomżo",
  },
  lowicz: {
    nominative: "Łowicz",
    genitive: "Łowicza",
    dative: "Łowiczowi",
    accusative: "Łowicz",
    instrumental: "Łowiczem",
    locative: "Łowiczu",
    vocative: "Łowiczu",
  },
  lubartow: {
    nominative: "Lubartów",
    genitive: "Lubartowa",
    dative: "Lubartowowi",
    accusative: "Lubartów",
    instrumental: "Lubartowem",
    locative: "Lubartowie",
    vocative: "Lubartowie",
  },
  lubin: {
    nominative: "Lubin",
    genitive: "Lubina",
    dative: "Lubinowi",
    accusative: "Lubin",
    instrumental: "Lubinem",
    locative: "Lubinie",
    vocative: "Lubinie",
  },
  malbork: {
    nominative: "Malbork",
    genitive: "Malborka",
    dative: "Malborkowi",
    accusative: "Malbork",
    instrumental: "Malborkiem",
    locative: "Malborku",
    vocative: "Malborku",
  },
  miedzychod: {
    nominative: "Międzychód",
    genitive: "Międzychodu",
    dative: "Międzychodowi",
    accusative: "Międzychód",
    instrumental: "Międzychodem",
    locative: "Międzychodzie",
    vocative: "Międzychodzie",
  },
  mielec: {
    nominative: "Mielec",
    genitive: "Mielca",
    dative: "Mielcowi",
    accusative: "Mielec",
    instrumental: "Mielcem",
    locative: "Mielcu",
    vocative: "Mielcu",
  },
  mikolow: {
    nominative: "Mikołów",
    genitive: "Mikołowa",
    dative: "Mikołowowi",
    accusative: "Mikołów",
    instrumental: "Mikołowem",
    locative: "Mikołowie",
    vocative: "Mikołowie",
  },
  myszkow: {
    nominative: "Myszków",
    genitive: "Myszkowa",
    dative: "Myszkowowi",
    accusative: "Myszków",
    instrumental: "Myszkowem",
    locative: "Myszkowie",
    vocative: "Myszkowie",
  },
  oswiecim: {
    nominative: "Oświęcim",
    genitive: "Oświęcimia",
    dative: "Oświęcimiowi",
    accusative: "Oświęcim",
    instrumental: "Oświęcimiem",
    locative: "Oświęcimiu",
    vocative: "Oświęcimiu",
  },
  ozorkow: {
    nominative: "Ozorków",
    genitive: "Ozorkowa",
    dative: "Ozorkowowi",
    accusative: "Ozorków",
    instrumental: "Ozorkowem",
    locative: "Ozorkowie",
    vocative: "Ozorkowie",
  },
  pabianice: {
    nominative: "Pabianice",
    genitive: "Pabianic",
    dative: "Pabianicom",
    accusative: "Pabianice",
    instrumental: "Pabianicami",
    locative: "Pabianicach",
    vocative: "Pabianice",
  },
  pajeczno: {
    nominative: "Pajęczno",
    genitive: "Pajęczna",
    dative: "Pajęcznu",
    accusative: "Pajęczno",
    instrumental: "Pajęcznem",
    locative: "Pajęcznie",
    vocative: "Pajęcznie",
  },
  pila: {
    nominative: "Piła",
    genitive: "Piły",
    dative: "Pile",
    accusative: "Piłę",
    instrumental: "Piłą",
    locative: "Pile",
    vocative: "Piło",
  },
  przemysl: {
    nominative: "Przemyśl",
    genitive: "Przemyśla",
    dative: "Przemyślowi",
    accusative: "Przemyśl",
    instrumental: "Przemyślem",
    locative: "Przemyślu",
    vocative: "Przemyślu",
  },
  pszczyna: {
    nominative: "Pszczyna",
    genitive: "Pszczyny",
    dative: "Pszczynie",
    accusative: "Pszczynę",
    instrumental: "Pszczyną",
    locative: "Pszczynie",
    vocative: "Pszczyno",
  },
  pulawy: {
    nominative: "Puławy",
    genitive: "Puław",
    dative: "Puławom",
    accusative: "Puławy",
    instrumental: "Puławami",
    locative: "Puławach",
    vocative: "Puławy",
  },
  "rawa-mazowiecka": {
    nominative: "Rawa Mazowiecka",
    genitive: "Rawy Mazowieckiej",
    dative: "Rawie Mazowieckiej",
    accusative: "Rawę Mazowiecką",
    instrumental: "Rawą Mazowiecką",
    locative: "Rawie Mazowieckiej",
    vocative: "Rawo Mazowiecka",
  },
  sandomierz: {
    nominative: "Sandomierz",
    genitive: "Sandomierza",
    dative: "Sandomierzowi",
    accusative: "Sandomierz",
    instrumental: "Sandomierzem",
    locative: "Sandomierzu",
    vocative: "Sandomierzu",
  },
  sanok: {
    nominative: "Sanok",
    genitive: "Sanoka",
    dative: "Sanokowi",
    accusative: "Sanok",
    instrumental: "Sanokiem",
    locative: "Sanoku",
    vocative: "Sanoku",
  },
  siedlce: {
    nominative: "Siedlce",
    genitive: "Siedlec",
    dative: "Siedlcom",
    accusative: "Siedlce",
    instrumental: "Siedlcami",
    locative: "Siedlcach",
    vocative: "Siedlce",
  },
  sieradz: {
    nominative: "Sieradz",
    genitive: "Sieradza",
    dative: "Sieradzowi",
    accusative: "Sieradz",
    instrumental: "Sieradzem",
    locative: "Sieradzu",
    vocative: "Sieradzu",
  },
  skierniewice: {
    nominative: "Skierniewice",
    genitive: "Skierniewic",
    dative: "Skierniewicom",
    accusative: "Skierniewice",
    instrumental: "Skierniewicami",
    locative: "Skierniewicach",
    vocative: "Skierniewice",
  },
  srem: {
    nominative: "Śrem",
    genitive: "Śremu",
    dative: "Śremowi",
    accusative: "Śrem",
    instrumental: "Śremem",
    locative: "Śremie",
    vocative: "Śremie",
  },
  "sroda-wielkopolska": {
    nominative: "Środa Wielkopolska",
    genitive: "Środy Wielkopolskiej",
    dative: "Środzie Wielkopolskiej",
    accusative: "Środę Wielkopolską",
    instrumental: "Środą Wielkopolską",
    locative: "Środzie Wielkopolskiej",
    vocative: "Środo Wielkopolska",
  },
  "stalowa-wola": {
    nominative: "Stalowa Wola",
    genitive: "Stalowej Woli",
    dative: "Stalowej Woli",
    accusative: "Stalową Wolę",
    instrumental: "Stalową Wolą",
    locative: "Stalowej Woli",
    vocative: "Stalowa Wolo",
  },
  starachowice: {
    nominative: "Starachowice",
    genitive: "Starachowic",
    dative: "Starachowicom",
    accusative: "Starachowice",
    instrumental: "Starachowicami",
    locative: "Starachowicach",
    vocative: "Starachowice",
  },
  stargard: {
    nominative: "Stargard",
    genitive: "Stargardu",
    dative: "Stargardowi",
    accusative: "Stargard",
    instrumental: "Stargardem",
    locative: "Stargardzie",
    vocative: "Stargardzie",
  },
  suwalki: {
    nominative: "Suwałki",
    genitive: "Suwałk",
    dative: "Suwałkom",
    accusative: "Suwałki",
    instrumental: "Suwałkami",
    locative: "Suwałkach",
    vocative: "Suwałki",
  },
  swidnik: {
    nominative: "Świdnik",
    genitive: "Świdnika",
    dative: "Świdnikowi",
    accusative: "Świdnik",
    instrumental: "Świdnikiem",
    locative: "Świdniku",
    vocative: "Świdniku",
  },
  swinoujscie: {
    nominative: "Świnoujście",
    genitive: "Świnoujścia",
    dative: "Świnoujściu",
    accusative: "Świnoujście",
    instrumental: "Świnoujściem",
    locative: "Świnoujściu",
    vocative: "Świnoujście",
  },
  szadek: {
    nominative: "Szadek",
    genitive: "Szadku",
    dative: "Szadkowi",
    accusative: "Szadek",
    instrumental: "Szadkiem",
    locative: "Szadku",
    vocative: "Szadku",
  },
  szczecinek: {
    nominative: "Szczecinek",
    genitive: "Szczecinka",
    dative: "Szczecinkowi",
    accusative: "Szczecinek",
    instrumental: "Szczecinkiem",
    locative: "Szczecinku",
    vocative: "Szczecinku",
  },
  tarnobrzeg: {
    nominative: "Tarnobrzeg",
    genitive: "Tarnobrzega",
    dative: "Tarnobrzegowi",
    accusative: "Tarnobrzeg",
    instrumental: "Tarnobrzegiem",
    locative: "Tarnobrzegu",
    vocative: "Tarnobrzegu",
  },
  "arnowskie-gory": {
    nominative: "Tarnowskie Góry",
    genitive: "Tarnowskich Gór",
    dative: "Tarnowskim Górom",
    accusative: "Tarnowskie Góry",
    instrumental: "Tarnowskimi Górami",
    locative: "Tarnowskich Górach",
    vocative: "Tarnowskie Góry",
  },
  tczew: {
    nominative: "Tczew",
    genitive: "Tczewa",
    dative: "Tczewowi",
    accusative: "Tczew",
    instrumental: "Tczewem",
    locative: "Tczewie",
    vocative: "Tczewie",
  },
  "tomaszow-lubelski": {
    nominative: "Tomaszów Lubelski",
    genitive: "Tomaszowa Lubelskiego",
    dative: "Tomaszowowi Lubelskiemu",
    accusative: "Tomaszów Lubelski",
    instrumental: "Tomaszowem Lubelskim",
    locative: "Tomaszowie Lubelskim",
    vocative: "Tomaszowie Lubelski",
  },
  "tomaszow-mazowiecki": {
    nominative: "Tomaszów Mazowiecki",
    genitive: "Tomaszowa Mazowieckiego",
    dative: "Tomaszowowi Mazowieckiemu",
    accusative: "Tomaszów Mazowiecki",
    instrumental: "Tomaszowem Mazowieckim",
    locative: "Tomaszowie Mazowieckim",
    vocative: "Tomaszowie Mazowiecki",
  },
  trzcianka: {
    nominative: "Trzcianka",
    genitive: "Trzcianki",
    dative: "Trzciance",
    accusative: "Trzciankę",
    instrumental: "Trzcianką",
    locative: "Trzciance",
    vocative: "Trzcianko",
  },
  ustka: {
    nominative: "Ustka",
    genitive: "Ustki",
    dative: "Ustce",
    accusative: "Ustkę",
    instrumental: "Ustką",
    locative: "Ustce",
    vocative: "Ustko",
  },
  wagrowiec: {
    nominative: "Wągrowiec",
    genitive: "Wągrowca",
    dative: "Wągrowcowi",
    accusative: "Wągrowiec",
    instrumental: "Wągrowcem",
    locative: "Wągrowcu",
    vocative: "Wągrowcu",
  },
  walcz: {
    nominative: "Wałcz",
    genitive: "Wałcza",
    dative: "Wałczowi",
    accusative: "Wałcz",
    instrumental: "Wałczem",
    locative: "Wałczu",
    vocative: "Wałczu",
  },
  wejherowo: {
    nominative: "Wejherowo",
    genitive: "Wejherowa",
    dative: "Wejherowu",
    accusative: "Wejherowo",
    instrumental: "Wejherowem",
    locative: "Wejherowie",
    vocative: "Wejherowie",
  },
  wielun: {
    nominative: "Wieluń",
    genitive: "Wielunia",
    dative: "Wieluniowi",
    accusative: "Wieluń",
    instrumental: "Wieluniem",
    locative: "Wieluniu",
    vocative: "Wieluniu",
  },
  "wodzislaw-slaski": {
    nominative: "Wodzisław Śląski",
    genitive: "Wodzisławia Śląskiego",
    dative: "Wodzisławowi Śląskiemu",
    accusative: "Wodzisław Śląski",
    instrumental: "Wodzisławiem Śląskim",
    locative: "Wodzisławiu Śląskim",
    vocative: "Wodzisławiu Śląski",
  },
  zamosc: {
    nominative: "Zamość",
    genitive: "Zamościa",
    dative: "Zamościowi",
    accusative: "Zamość",
    instrumental: "Zamościem",
    locative: "Zamościu",
    vocative: "Zamościu",
  },
  zary: {
    nominative: "Żary",
    genitive: "Żar",
    dative: "Żarom",
    accusative: "Żary",
    instrumental: "Żarami",
    locative: "Żarach",
    vocative: "Żary",
  },
  zawiercie: {
    nominative: "Zawiercie",
    genitive: "Zawiercia",
    dative: "Zawierciu",
    accusative: "Zawiercie",
    instrumental: "Zawierciem",
    locative: "Zawierciu",
    vocative: "Zawiercie",
  },
  zgierz: {
    nominative: "Zgierz",
    genitive: "Zgierza",
    dative: "Zgierzowi",
    accusative: "Zgierz",
    instrumental: "Zgierzem",
    locative: "Zgierzu",
    vocative: "Zgierzu",
  },
  zyrardow: {
    nominative: "Żyrardów",
    genitive: "Żyrardowa",
    dative: "Żyrardowowi",
    accusative: "Żyrardów",
    instrumental: "Żyrardowem",
    locative: "Żyrardowie",
    vocative: "Żyrardowie",
  },
  "kedzierzyn-kozle": {
    nominative: "Kędzierzyn-Koźle",
    genitive: "Kędzierzyna-Koźla",
    dative: "Kędzierzynowi-Koźlu",
    accusative: "Kędzierzyn-Koźle",
    instrumental: "Kędzierzynem-Koźlem",
    locative: "Kędzierzynie-Koźlu",
    vocative: "Kędzierzynie-Koźle",
  },
};

// Get city in specific grammatical case
export function getCityInCase(
  citySlug: string,
  grammaticalCase: PolishCase
): string {
  const declension = cityDeclensions[citySlug];
  if (!declension) {
    // Fallback to display name if declension not found
    return getCityDisplayName(citySlug);
  }

  switch (grammaticalCase) {
    case PolishCase.NOMINATIVE:
      return declension.nominative;
    case PolishCase.GENITIVE:
      return declension.genitive;
    case PolishCase.DATIVE:
      return declension.dative;
    case PolishCase.ACCUSATIVE:
      return declension.accusative;
    case PolishCase.INSTRUMENTAL:
      return declension.instrumental;
    case PolishCase.LOCATIVE:
      return declension.locative;
    case PolishCase.VOCATIVE:
      return declension.vocative;
    default:
      return declension.nominative;
  }
}

// Get all declensions for a city
export function getCityDeclension(citySlug: string): CityDeclension | null {
  return cityDeclensions[citySlug] || null;
}

// Generate content with proper grammar for different contexts
export function generateCityContent(citySlug: string) {
  const declension = getCityDeclension(citySlug);
  if (!declension) return null;

  return {
    // Different grammatical contexts
    contexts: {
      // "Strona internetowa w Warszawie" (locative)
      location: `w ${getCityInCase(citySlug, PolishCase.LOCATIVE)}`,

      // "Firma z Warszawy" (genitive)
      origin: `z ${getCityInCase(citySlug, PolishCase.GENITIVE)}`,

      // "Usługi dla Warszawy" (genitive)
      target: `dla ${getCityInCase(citySlug, PolishCase.GENITIVE)}`,

      // "Mieszkańcom Warszawy" (dative)
      residents: `mieszkańcom ${getCityInCase(citySlug, PolishCase.GENITIVE)}`,

      // "Obsługujemy Warszawę" (accusative)
      service: `obsługujemy ${getCityInCase(citySlug, PolishCase.ACCUSATIVE)}`,

      // "Razem z Warszawą" (instrumental)
      together: `razem z ${getCityInCase(citySlug, PolishCase.INSTRUMENTAL)}`,

      // "O Warszawie" (locative)
      about: `o ${getCityInCase(citySlug, PolishCase.LOCATIVE)}`,
    },

    // Ready-to-use phrases for content
    phrases: {
      webDesignService: `Tworzenie stron internetowych w ${getCityInCase(
        citySlug,
        PolishCase.LOCATIVE
      )}`,
      localBusiness: `Lokalna firma z ${getCityInCase(
        citySlug,
        PolishCase.GENITIVE
      )}`,
      forResidents: `Dla mieszkańców ${getCityInCase(
        citySlug,
        PolishCase.GENITIVE
      )}`,
      servingCity: `Obsługujemy ${getCityInCase(
        citySlug,
        PolishCase.ACCUSATIVE
      )}`,
      aboutCity: `O ${getCityInCase(citySlug, PolishCase.LOCATIVE)}`,
      welcomeCity: `Witaj ${getCityInCase(citySlug, PolishCase.VOCATIVE)}!`,
      workingWith: `Współpracujemy z ${getCityInCase(
        citySlug,
        PolishCase.INSTRUMENTAL
      )}`,
      citySpecialist: `Specjalista ${getCityInCase(
        citySlug,
        PolishCase.GENITIVE
      )}`,
    },

    // All grammatical forms for reference
    allForms: declension,
  };
}
