"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { getDocuments, getBlogPosts } from "@/common/firebase";
import { Post } from "@/types";
import { FaFacebook, FaTiktok } from "react-icons/fa";

export default function Footer() {
  const [blogPosts, setBlogPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchBlogPosts = async () => {
      try {
        const [collectionDocs, legacyDoc]: any = await Promise.all([
          getDocuments("blog"),
          getBlogPosts(),
        ]);

        const legacyPosts = Array.isArray(legacyDoc?.posts)
          ? legacyDoc.posts
          : [];
        const combined: Post[] = [...(collectionDocs || []), ...legacyPosts];

        // Filter out city-based auto-generated posts, show only real blog posts
        const realBlogPosts = combined.filter(
          (post) =>
            !post.isAutogenerated && (post.slug || post.url || post.postId)
        );

        setBlogPosts(realBlogPosts);
      } catch (error) {
        console.error("Error fetching blog posts:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchBlogPosts();
  }, []);

  return (
    <footer className="bg-black/90 text-white py-16 px-4 relative z-50">
      <div className="max-w-[90vw] mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Company Info */}
          <div className="lg:col-span-1">
            <Link href="/" className="block mb-6">
              <Image
                src="/assets/quixy-logo.png"
                width={200}
                height={80}
                alt="Quixy Studio Logo"
                className="w-auto h-16"
                priority
              />
            </Link>
            <p className="text-gray-300 text-sm leading-relaxed mb-6 font-sans font-light max-w-sm">
              W Quixy znajdziesz pracę zdalną, zlecenia i stworzysz profil firmy
              lub freelancera.
            </p>

            {/* Contact Info */}
            <div className="space-y-3">
              <span className="text-[#B4FC2D] text-lg mb-4 font-gotham font-light">
                Kontakt
              </span>
              <div className="text-gray-300 text-sm space-y-2 font-sans">
                <p>
                  <span className="font-bold">Email:</span>{" "}
                  <a
                    href="mailto:wesiudev@gmail.com"
                    className="text-[#3EE7C0] hover:text-[#B4FC2D] transition-colors font-light"
                  >
                    kontakt@quixy.pl
                  </a>
                </p>
                <p>
                  <span className="font-bold">Telefon:</span>{" "}
                  <a
                    href="tel:+48721417154"
                    className="text-[#3EE7C0] hover:text-[#B4FC2D] transition-colors font-light"
                  >
                    +48 721 417 154
                  </a>
                </p>
              </div>
            </div>
          </div>

          {/* Legal & Additional Links */}
          <div>
            <div className="space-y-2 text-sm font-sans">
              <Link
                href="/contact"
                className="block text-gray-300 hover:text-[#3EE7C0] transition-colors py-1 font-light"
              >
                Kontakt
              </Link>
              <Link
                href="/login"
                className="block text-gray-300 hover:text-[#3EE7C0] transition-colors py-1 font-light"
              >
                Logowanie
              </Link>
              <Link
                href="/register"
                className="block text-gray-300 hover:text-[#3EE7C0] transition-colors py-1 font-light"
              >
                Rejestracja
              </Link>
              <Link
                href="/news"
                className="block text-gray-300 hover:text-[#3EE7C0] transition-colors py-1 font-light"
              >
                Aktualności
              </Link>
              <Link
                href="/blog"
                className="block text-gray-300 hover:text-[#3EE7C0] transition-colors py-1 font-light"
              >
                Blog
              </Link>
              <Link
                href="/regulamin"
                className="block text-gray-300 hover:text-[#3EE7C0] transition-colors py-1 font-light"
              >
                Regulamin
              </Link>
              <Link
                href="/sitemap.xml"
                className="block text-gray-300 hover:text-[#3EE7C0] transition-colors py-1 font-light"
              >
                Mapa strony
              </Link>
            </div>
          </div>
        </div>

        {/* Bottom Section */}
        <div className="border-t border-gray-700 mt-12 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="text-gray-400 text-sm font-sans font-light">
              © {new Date().getFullYear()} Quixy Studio. Wszystkie prawa
              zastrzeżone.
            </div>

            {/* Social Media Links */}
            <div className="flex items-center space-x-4">
              <Link
                title="Strony Internetowe WWW z Cennikiem Grudziądz Tiktok"
                target="_blank"
                href="https://www.tiktok.com/@strony_www_grudziadz"
                className="flex items-center"
              >
                <FaTiktok className="text-2xl text-white" />
              </Link>
              <Link
                title="Strony Internetowe WWW z Cennikiem Grudziądz Facebook"
                href="https://www.facebook.com/profile.php?id=61579945978455"
                target="_blank"
                className="flex items-center"
              >
                <FaFacebook className="text-2xl text-white" />
              </Link>
            </div>
          </div>

          {/* SEO Footer Text */}
          <div className="mt-6 text-center">
            <p className="text-gray-500 text-xs max-w-4xl mx-auto font-sans font-light">
              Quixy Studio - Agencja marketingu cyfrowego specjalizująca się w
              tworzeniu stron internetowych, sklepów online, kampaniach Google
              Ads oraz zarządzaniu social media. Obsługujemy klientów w całej
              Polsce, oferując kompleksowe rozwiązania digital marketingu dla
              firm każdej wielkości.
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
}
